"""add therapist overrides

Revision ID: 553f9e15086c
Revises: 78b183e00fd1
Create Date: 2026-09-20 21:57:28.963034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f9e15086c'
down_revision: Union[str, Sequence[str], None] = '78b183e00fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_off', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_overrides_date'), 'therapist_overrides', ['date'], unique=False)
    op.create_index(op.f('ix_therapist_overrides_id'), 'therapist_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_therapist_overrides_therapist_id'), 'therapist_overrides', ['therapist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_therapist_overrides_therapist_id'), table_name='therapist_overrides')
    op.drop_index(op.f('ix_therapist_overrides_id'), table_name='therapist_overrides')
    op.drop_index(op.f('ix_therapist_overrides_date'), table_name='therapist_overrides')
    op.drop_table('therapist_overrides')
    # ### end Alembic commands ###
